### ISSUE TITLE
To discuss: timer considerations

### ISSUE THREAD

**Issue by ekron** [tesapp/tes-xapi#1]
I was keeping started - paused - resumed as separate, explicit timing statements. The metaphor being a timer - often surfaced in a UI as "play" and "pause" buttons.

Adjourned doesn't infer a timer in quite the same way - you don't general "adjourn" a play button, if you know what I mean.

So I reconsidered things. Perhaps keeping timing explicit and as separate statements is just an added complication? See what you think about a more minimal approach using just opened - adjourned - resumed - closed. Timing can be extrapolated but isn't expressed as separate statements. 

Another option is to keep started - paused - resumed, and keep timing explicit. And add adjourned too to cover cases where timing isn't used but the event is expressly adjourned.

**Comment by garemoko** [comment]
I'm not keen on the timer metaphor as I don't think it's what people generally do for events outside of sporting events.
