### ISSUE TITLE
Planned start datetime and duration

### ISSUE THREAD

**Issue by garemoko** [tesapp/tes-xapi#12]
We should put a planned start time and duration to the Initialized/Scheduled event.

**Comment by ekron** [comment]
Thanks, good idea. Could you give me an example of what you propose?

**Comment by garemoko** [comment]
It would be a extension or two in the context I think.

**Comment by ekron** [comment]
Happy to use whatever identifiers you want, I've added a couple of placeholders. Hopefully it's what you have in mind.
