### ISSUE TITLE
More explanation of result and timestamp

### ISSUE THREAD

**Issue by garemoko** [tesapp/tes-xapi#14]
I'm adding some information about result and timestamp to the Simple Attendance. It would be nice to see that same logic applied to all of the Detailed Attendance tracking events.

**Comment by ekron** [comment]
Can you give me a quick example of what you envisage for one of the Detailed Attendance statements?

**Comment by garemoko** [comment]
The section I'm referring to in Simple Attendance is:

"The statement's timestamp always represents the start of the event and the Result Duration can optionally be used to record the length of the event. Activity Providers can issue multiple statements with the same timestamp and activity id to refer to the same event, updating the duration with each statement. In this case, the statement with the largest duration value is considered to represent the final duration. Activity Providers should not issue 'attended' statements with the same Activity Id and different timestamps; to do so would be to record conflicting information about the start time of the event."

We could say something along these lines for each of the events where time is relevant, so for example scheduled the timestamp is the point in time that the scheduling happened, not when the event is scheduled for; there is no duration. For joined, the timestamp is the point in time when the person joined and duration represents the event time elapsed (time whilst the event is open). 

is that helpful?

**Comment by ekron** [comment]
Yes, thanks. It's clear now.
