### ISSUE TITLE
Timestamp for attendance needs to be able to change

### ISSUE THREAD

**Issue by emlynoregan** [tesapp/tes-xapi#23]
"Activity Providers should not issue 'attended' statements with the same Activity Id and different timestamps. The statements would combine to create conflicting data about the start time of the event."

Our system allows the user to change the start time of an attendance, as they will often need to correct mistakes. You can uniquely identify an attendance using the id in the object, so there's no reason to also rely on the timestamp, this should be able to change.

**Comment by garemoko** [comment]
The the requirement here is to prevent a case where one statement says Bob attended meeting 1 starting at 10am and Sue attended meeting 1 starting at 11am. The meeting either started at 10 or 11. If the start time on the original statement was an error, it should be voided and reissued. 

If we agree with that approach, we should make that clearer in the recipe. 

Thoughts?

**Comment by emlynoregan** [comment]
"If the start time on the original statement was an error, it should be voided and reissued."

That sounds right to me; there should actually only be one non-voided simple attendance statement per attendance. Ok, that should be made explicit in the recipe. Rather than rules about longest duration wins, just say that there can only be one non-voided statement.

**Comment by garemoko** [comment]
A thought: it's very possible that multiple applications and users might issue statements about the same event. That would make only one statement per event unreasonable. It could also make the rules about start time difficult. We'll have to have a think!

**Comment by emlynoregan** [comment]
Maybe we need two different timestamps?

The timestamp for the statement should probably be the TES at which the
statement was generated.

Add "starts", " ends", ... as what? Extra info in the object?

The statement would semantically be:

<actor> attended <event start:... ends:...> and this was true as at
<timestamp>

**Comment by emlynoregan** [comment]
I don't think the two-users or two-systems problem is soluble in general. But what would that mean? 

Actually, why are we even including duration? 

This attendance statement would be simpler if it just talked about attendance.

If that was true, then the real attendance of an event could be considered to be the union of the actors in all simple attendance statements about the event.

Duration could be handled as a property of an event, like start, end, name, others?

How are properties normally handled? How would you say <actor> says duration of <event> is <duration> ?

**Comment by emlynoregan** [comment]
How would you say 
[actor] says duration of [event] is [duration] 
?

(Sorry, mobile browser messed up my last paragraph)

**Comment by ekron** [comment]
I've tentatively updated the text to reflect the discussion so far.

I agree multiple users and multiple systems could issue statements about the same event. You might have several authorities, instructors, or several observers issuing statements? Resolving which statement is the definitive one seems out of scope? (Perhaps LRS's job is to record the divergent statements and present them to end-users for analysis and disambiguation?)

**Comment by emlynoregan** [comment]
I think this is the right approach. However, it's worth noting that this makes the simple recipe very much harder to implement; you have to store the id of the "active" statement, so you can void it if you need to resend.

**Comment by ekron** [comment]
Or you could [GET](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#723-getstatements) the statement from the LRS by activity id and verb, void what the id that is returned and reissue a statement.

**Comment by garemoko** [comment]
I'm really not keen on the idea of voiding statements by other activity providers. I think you need to be able to issue multiple statements about the event in order for different APs to record attendees. Imagine a conference with 1000s of attendees for example. Each attendee might generate a statement of attendance. 

I think the better solution is to be less strict on the timestamp within simple attendance. If you want to know when the event absolutely started, use detailed attendance.

**Comment by ekron** [comment]
No worries Andrew, good feedback. I have updated the Simple Attendance notes to reflect the change. I'll tentatively close this issue now.
