### ISSUE TITLE
Simple Attendance: Most recent statement (via "stored") should be considered definitive

### ISSUE THREAD

**Issue by emlynoregan** [tesapp/tes-xapi#24]
This statement is really stating the state of the attendance; ie: it contains all information about the attendance as a snapshot. Duration might change both up and down over time as user modify duration ("the attendance went for 5 hours, oops no it went for 3 hours"). Shouldn't the last statement received be considered definitive?

**Comment by garemoko** [comment]
You can't rely on stored to judge the definitiveness of statements as on distributed systems a statement issued earlier could easily arrive later in one or more LRS in the system. 

Voiding should be used to correct errors.

**Comment by emlynoregan** [comment]
Makes sense. The voiding approach fixes this.

**Comment by emlynoregan** [comment]
This should be removed from the spec:
"Then the statement with the largest result.duration is considered to be the final duration and definitive statement about the event."

**Comment by ekron** [comment]
Closed, we can handle this in #23.
