### ISSUE TITLE
Simple vs Detailed Attendance; does it make sense to use both?

### ISSUE THREAD

**Issue by emlynoregan** [tesapp/tes-xapi#26]
We're implementing Detailed attendance which also necessitates Simple attendance. Do we really need to implement Simple attendance? It seems redundant.

**Comment by garemoko** [comment]
If all systems that will ever interact always use Detailed Attendance then Simple Attendance is redundant. Implementing both ensures you're interoperable with systems that only adopt Simple Attendance, at least for the basic information about the event.

**Comment by emlynoregan** [comment]
Yup, ok. We'll stick with implementing both for now.
