### ISSUE TITLE
adjourned duration

### ISSUE THREAD

**Issue by garemoko** [tesapp/tes-xapi#28]
In reviewing the recipe for it to go on registry @brianjmiller flagged up a number of points, most of which are covered in #27. Please take a look at that and see what you think; I don't think there's any significant functional changes. 

One item I didn't include in the PR is that Brian feels the duration on the adjourned statement should be the time since the last 'opened' or 'resumed' statement rather than that total meeting time to date. This would be a better match to the 'resumed' duration which is the time since the meeting was adjourned. 

@ekron @emlynoregan what are your thoughts on this? Presumably you have already put some work into this; do you agree with the suggestion and how much pain will it cause you to change it?

**Comment by ekron** [comment]
Thanks Andrew. PR looked good to me, have merged it.

I think Brian's suggestion about adjournment statement result.duration is a good one. I have tentatively updated the recipe in the attendance-0_1_1 branch with the suggestion.

In terms of implementation, I'll leave that up to @emlynoregan to respond to.
