### ISSUE TITLE
Copy editting

### ISSUE THREAD

**Issue by garemoko** [tesapp/tes-xapi#5]
I'd like to do some copy editing (capitalisation of words and things like that) before this is released as a ready to try recipe. Raising this issue to remind me to do a PR.

**Comment by garemoko** [comment]
I'm working on this now and making fairly big changes. Will submit a PR soon for discussion.

**Comment by garemoko** [comment]
I got as far as the start of 'Properties that Apply to All Statements'. I'll make a PR now and pick back up tomorrow.

**Comment by ekron** [comment]
Thanks Andrew. Can I suggest that you reference this issue with your next pull request. E.g #5 in the body of you pull request.
